name: Dart CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Dart
        uses: dart-lang/setup-dart@v1

      - name: Install dependencies
        run: dart pub get

      - name: Install protoc
        run: sudo apt-get install -y protobuf-compiler

      - name: Activate protoc_plugin
        run: dart pub global activate protoc_plugin

      - name: Generate Protobufs
        run: |
          export PATH="$PATH":"$HOME/.pub-cache/bin"
          python3 generate_proto.py

    #   - name: Run analyzer
    #     run: dart analyze

      - name: Run unit tests
        run: dart test test/unit/